const REMARKS = [
  "the graphpaper is only for aesthetics",
  "it turned my laptop into molten metal!",
  "sounds like a rhythm game",
  "how to type hex digits 10-15? just don't!",
  "oh god why doesn't it round 10^-16 to zero",
  "nobody knows what the sidebar does",
  "because you wanted desmos to be open source",
  "its developers thought ≱ was useful",
  "what is the logo hiding",
  "the ‘go to sleep’ node type is not implemented yet",
  "nya? like the cat noise? (yes)",
  "what even does ⊙ do",
  "it can write decimals in base 5, but not read them",
  "it has uscript support",
  "easier to extend than a tungsten cube",
  "variables are for silly people",
  "my favorite color palette: modern house",
  "i still don't know why it exists",
  "they added \\over before y=2",
  "mrrp meow",
  "how even do you grow the piecewise function",
  "it’s like ithkuil decomposer, but totally different",
  "it’s shaders for the rest of us",
  "tbh it’s only so sakawi can say ‘nya’ more",
  "car <3",
  "where bedtime is 29:00",
  "brought to you by sleep deprivation",
  "sponsored by zSnout",
  "in awe of the desmos team tbh",
  "we once defined eˣ to just be x 😭",
  "its order of operations is so cursed",
  "now with vertical lists!",
  "first class support for typing matrices",
  "oklch >>> hsv",
  "our fractals are so good it’s silly",
  "currently on type system #3",
  "where numbers come in three precision levels",
  "even our colors can be approximate",
  "LaTeX parsing or— THE SECOND ONE",
  "copy-paste easy to implement: famous last words",
  "the error messages are doubled because why not",
  "experience the joy of floating point numbers",
  "lines are impossible",
  "most of these are outdated. enjoy them anyway >:3",
  "generic pointer events my beloved",
  "more blue than expected",
  "everything has been coded at least twice",
  "options to inits to exts to packages",
  "sorry we keep taking down the site",
  "now with quaternions!",
  "angle bisector ≠ triangle median",
  "use @ to type tokens",
  "'mom can we get a desmos?' 'no, we have a desmos at home'",
  "intuitive images 🙁 images on line segments 🤩",
  "slowly making an operating system",
  "WE HAVE KEYBOARD SHORTCUTS :spair:",
  "monkey patching? sounds hacky.",
  "so much documentation that it's unhelpful",
  "lock in 😐",
  "¡try spanish factorial notation!",
  "on our way to make a CAS system...",
]

export const REMARK = REMARKS[Math.floor(REMARKS.length * Math.random())]!
