export const NYALANG_PACKAGES_BUILTIN = {
  __proto__: null,
  "nya:special": ()=>Promise.resolve({default:{"name":"special functions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["special"]} as const}),
  "nya:2d/point": ()=>Promise.resolve({default:{"name":"2D points","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["2d/point"]} as const}),
  "nya:2d/geo": ()=>Promise.resolve({default:{"name":"2D geometry","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["2d/geo"]} as const}),
  "nya:2d/geo/complex": ()=>Promise.resolve({default:{"name":"2D geometry via complex numbers","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["2d/geo/complex"]} as const}),
  "nya:2d/geo/complex-algebra": ()=>Promise.resolve({default:{"name":"algebra on 2D geometry","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["2d/geo/complex-algebra"]} as const}),
  "nya:data/distributions": ()=>Promise.resolve({default:{"name":"distributions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["data/distributions"]} as const}),
  "nya:data/stats/real": ()=>Promise.resolve({default:{"name":"rudimentary statistics functions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["data/stats/real"]} as const}),
  "nya:data/stats/complex": ()=>Promise.resolve({default:{"name":"rudimentary complex statistics functions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["data/stats/complex"]} as const}),
  "nya:4d/two-complex": ()=>Promise.resolve({default:{"name":"4D points (bicomplex)","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["4d/two-complex"]} as const}),
  "nya:4d/point": ()=>Promise.resolve({default:{"name":"4D points","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["4d/point"]} as const}),
  "nya:4d/quaternion": ()=>Promise.resolve({default:{"name":"quaternions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["4d/quaternion"]} as const}),
  "nya:color/extras": ()=>Promise.resolve({default:{"name":"oklch() and oklab()","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["color/extras"]} as const}),
  "nya:color/core": ()=>Promise.resolve({default:{"name":"rgb() and hsv()","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["color/core"]} as const}),
  "nya:real": ()=>Promise.resolve({default:{"name":"core real operations","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["real"]} as const}),
  "nya:real/trig-hyperbolic": ()=>Promise.resolve({default:{"name":"real hyperbolic trig","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["real/trig-hyperbolic"]} as const}),
  "nya:real/trig": ()=>Promise.resolve({default:{"name":"real trigonometry","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["real/trig"]} as const}),
  "nya:real/erf": ()=>Promise.resolve({default:{"name":"real erf","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["real/erf"]} as const}),
  "nya:real/number-theory": ()=>Promise.resolve({default:{"name":"real round()","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["real/number-theory"]} as const}),
  "nya:complex": ()=>Promise.resolve({default:{"name":"complex numbers","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["complex"]} as const}),
  "nya:complex/trig-hyperbolic": ()=>Promise.resolve({default:{"name":"complex hyperbolic trig","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["complex/trig-hyperbolic"]} as const}),
  "nya:complex/trig": ()=>Promise.resolve({default:{"name":"complex trigonometry","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["complex/trig"]} as const}),
  "nya:complex/erf": ()=>Promise.resolve({default:{"name":"complex erf() and faddeeva()","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["complex/erf"]} as const}),
  "nya:complex/number-theory": ()=>Promise.resolve({default:{"name":"complex number theory","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["complex/number-theory"]} as const}),
  "nya:core/bool": ()=>Promise.resolve({default:{"name":"boolean coercions","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["core/bool"]} as const}),
  "nya:3d/point": ()=>Promise.resolve({default:{"name":"3d points","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["3d/point"]} as const}),
  "nya:3d/geo": ()=>Promise.resolve({default:{"name":"3D geometry","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["3d/geo"]} as const}),
  "nya:gamma/factorial": ()=>Promise.resolve({default:{"name":"complex factorial","label":"<TODO: no label>","category":"auto-generated (nyalang)","deps":[],"scripts":["gamma/factorial"]} as const}),
} as const

export const NYALANG_PACKAGES_ADDONS = {
  __proto__: null,
} as const
